# Generated by Django 2.2.5 on 2019-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('done', models.BooleanField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
